version: '3'

networks:
  api-network: #connect api and redis
    driver: bridge
  mongo-network: #connnect api and mongodb
    driver: bridge
  express-network: #connnet mongoDB and mongo express
    driver: bridge

  

services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017
      - REDIS_URI=redis://redis
      - ENABLE_WRITING_HANDLERS=false 
    depends_on:
      - mongodb
    networks:
      - api-network      
      - mongo-network

  redis: #The Redis image does not require variables.
    image: redis:alpine
    container_name: redis
    networks:
      - api-network  

  mongodb:
    container_name: mongoDB 
    image: mongo:8.0-rc
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - moviesdata:/data/db
    networks:
      - mongo-network
      - express-network

  seeder:
    image: mongo_seeder
    depends_on:
      - mongodb
    networks:
      - mongo-network

  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - express-network
    depends_on:
      - mongodb

volumes:
  moviesdata:

