services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017
      - REDIS_URI=redis://redis
      - ENABLE_WRITING_HANDLERS=false 

  redis: #The Redis image does not require variables.
    image: redis:alpine
    container_name: redis

  mongodb:
    container_name: mongoDB 
    image: mongo:8.0-rc
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=password #Should be same with .env 